export class AnamneseModel {
    public EmpIdf: number;
    public AluIdf: number;
    public AnaIdf: number;
    public AnaData: Date;
    public AnaConvenio: string;
    public AnaRespEmergencia: string;
    public AnaRespEmeFone: string;
    public AnaRespEmeObs: string;
    public AnaTipoSangue: string;
    public AnaHipertenso: string;
    public AnaDiabetes: string;
    public AnaCardiaco: string;
    public AnaLabirintite: string;
    public AnaAsma: string;
    public AnaConvulcoes: string;
    public AnaAlergia: string;
    public AnaDepressao: string;
    public AnaOutras: string;
    public AnaMedicamentos: string;
    public AnaCirurgia: string;
    public AnaOsseo: string;
    public AnaFratura: string;
    public AnaCns6: string;
    public AnaTratamento: string;
    public AnaStatus: string;
    public DataInc: Date;
    public DataAlt: Date;
}